#ifndef H_ERRORS_H
#define H_ERRORS_H


enum error {
    INCORRECT_NUMBER_OF_COMMAND_LINE_ARGUMENTS = 1,
    INPUT_FILE_FAILED_TO_OPEN,
    INPUT_FILE_FAILED_TO_CLOSE,
    PARSING_ERROR_EMPTY_INPUT_FILE,
    OUTPUT_FILE_FAILED_TO_OPEN,
    OUTPUT_FILE_FAILED_TO_CLOSE,
    PARSING_ERROR_INVALID_FORMAT,
    STACK_OVER_FLOW,
    STACK_EMPTY,
};



#endif
